apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: flask-deploy-hpa
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flask-deploy
